server:
    port: 8081
eureka:
    instance:
        instance-id: order-api-8081
        prefer-ip-address: true # 访问路径可以显示 IP
env: dev

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.3.15:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 402932
    driver-class-name: com.mysql.cj.jdbc.Driver
